# .github/codespace.yaml
name: PROJECT_NAME_PLACEHOLDER
on_create:
  tasks:
    - name: Install Dependencies
      shell: bash
      run: |
        bash .devcontainer/conda_setup.sh
forwardPorts: 
  - 8000  # Default port for web services, update as needed
