# .github/codespace.yml
name: "Project Template Codespace"
on_create:
  tasks:
    - name: Install Dependencies
      run: |
        conda env create -f environment.yaml
        conda activate myenv
        pip install -r requirements.txt
forwardPorts: 
  - 8000  # Default port for web services, update as needed
