name: myenv
channels:
  - defaults
dependencies:
  - python=3.10
  - sphinx
  - pip
  - pip:
    - pip-tools
    - pytest==7.2.0
    - tox==4.0.8
    - behave==1.2.6
    - black==21.12b0
    - sphinx==7.0.1
    - sphinxcontrib-plantuml==0.25
    - pip-tools==6.13.0